name: UltraChat
version: 2.0
main: me.ryandw11.ultrachat.UltraChat
author: Ryandw11
description: A chat formatting plugin.
depend: [Vault, PlaceholderAPI]
commands:
    chat:
     description: The main command for the plugin.
     aliases: [UltraChat, uchat, ultrac, uc]
    sc:
      description: The staff chat command.
      aliases: [Staffchat, schat, staffc]
    sctoggle:
      description: Toggle the staff chat from showing up.
      aliases: [StaffchatToggle, schattoggle, staffct, sct]
    spy:
      description: See commands that other players type.
      aliases: [spycmd, cmds, uspy, ucspy]
    color:
      description: Change your chat color.
      aliases: [ccolor, chatcolor, uchatcolor, uccolor, chat color]
    channel:
      description: Change the channel you are using or display the help.
      aliases: [chan, cn, ch]